---
title: "R Markdown"
author: "Albert Y. Kim"
date: "September 21, 2016"
output: ioslides_presentation
---

<style>
h2 { 
 color: #3399ff;		
}
h3 { 
 color: #3399ff;		
}
slides > slide.backdrop {
  background: white;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```




## What is R Markdown?

R Markdown is an authoring format that enables easy creation of dynamic
documents, presentations, and reports from R.

It is based on the Markdown, whics allows you to write using an easy-to-read,
easy-to-write plain text format, then convert it to HTML.




## Example of Markdown (Not R Markdown)

[SetUp](https://github.com/Middlebury-Data-Science/SetUp/blob/master/README.md) page for this class. 

* In your browsers, you see the output of the markdown file `README.md`
* To see raw input file `README.md`, click on the "RAW" button




## R Markdown

R Markdown is a combination of

* R code, output, and graphics
* Markdown

that can **knit** (i.e. output) to either

* PDF: for polished reports
* HTML: for publishing results on the web as in HW-0
* Word: yuck




## Resources

* Cheatsheet
* RStudio Reference: Menu bar -> Help -> Markdown Quick Reference
* [R Markdown Debugging](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/edit?usp=sharing)




## HW-1

You will be submitting all HW's in this class via R Markdown.

* Do all your work in a separate `.R` script first
* Copy over code little-by-little to the `.Rmd` file, making sure to Knit several times along the way.
* Do **NOT** submit a non-Knitting `.Rmd` file. If a section of code does not work, comment it out.
* If you have problems, check all the steps in the [R Markdown Debugging](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/edit?usp=sharing) guide.

